### ISSUE TITLE
installation steps in Readme.md does not work

### ISSUE THREAD

**Issue by timrandg** [Teichlab/gene2probe#1] opened 2024-07-30 19:55 UTC
I followed the installation steps, but the pybedtools will not import. The issue seems to be that python 3.11 and pydebtools are not compatible. I reverted to python 3.7, which allowed import pybedtools in ipython. 

Jupyter may not recognize the python used in the conda env...that can be fixed with nb_conda_kernels. 

conda install -n <notebook_env> nb_conda_kernels

Be sure to select the kernel associated with your env. 

I may be back with other issues.

**Comment by timrandg** [comment] 2024-07-30 21:54
I added an install.sh script that may make the installation process better. Please see pull request.

**Comment by ioansarr** [comment] 2024-07-31 08:05
Hi Tim! Thank you for using our tool and for reporting this issue.

In my conda installation, I am using python 3.11.9 and pybedtools 0.10.0 without any issues. Could you please forward the error you encountered during installation?

To use the jupyter notebooks interactively (as intended), it is indeed important to set up an ipykernel and select the correct kernel in the jupyter lab session. I will add instructions for this to the README file.

**Comment by irenemaring** [comment] 2024-11-11 03:38
I run also into the same problem. I think the issue is that when you install bedtools it downgrades python version.
I fixed it by installing only pybedtools and then gene2probe
`conda install -n gene2probe_env --channel conda-forge --channel bioconda pybedtools`
`pip install git+https://github.com/Teichlab/gene2probe.git`

**Comment by ioansarr** [comment] 2024-11-11 15:56
Thank you both for the input. I have updated the installation instructions and tested in a clean install. Closing the issue now but please let me know if problems appear again.

**Closed as completed by ioansarr** 2024-11-11 15:56 UTC
